{"name": "test_01_check", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: 400 != 200", "trace": "self = <auth_controller.AuthController testMethod=test_01_check>\n\n    @pytest.mark.xfail\n    def test_01_check(self):\n        data = {\n            \"phone\": \"995551554599\"\n        }\n    \n        headers = {\n            'content-type': 'application/json',\n            # 'Authorization': 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDQ2xaTFhra1NHaEMxWkp2bkl0ZXNRdnFUUC0wbjVfQ0VLOTFBbUNndkZZIn0.eyJleHAiOjE2OTk5NzE1MTgsImlhdCI6MTY5OTk2NzkxOCwianRpIjoiMmZmMzUyZDMtNzVhOS00MzdjLWIxOGMtMDU5ODRkZDBlMGU5IiwiaXNzIjoiaHR0cHM6Ly9hcHBkZXYua2VlcHoubWU6ODA4MC9hdXRoL3JlYWxtcy9zd2VlZnQiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZmM4ZGMyMmQtZmVmNS00MzdiLTllMmUtNWEyNzA2YWJjODRjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic3dlZWZ0LWFwaS1nYXRld2F5Iiwic2Vzc2lvbl9zdGF0ZSI6IjZiNTU1ZjM4LTVlMzktNDVlOC1iMjNkLTM2MjM3NWZiZDU5OSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1zd2VlZnQiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvZmZsaW5lX2FjY2VzcyBwcm9maWxlIGluZGl2aWR1YWxfdXNlciBlbWFpbCB0ZXN0IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJkYXRhYmFzZV9pZCI6IntcInVzZXJJZFwiOlwiN2Q3ZWIzYmUtMmNlYi00OGJmLTlmMDUtMTZmYjhkNDcwZWM3XCJ9IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiOTk1NTk5OTg5OTgxIn0.Igd1CIruooAjI5tk7auVpMQ1hoKouaDKx_neJKhjdUO6oWN9yYrDsbV5Qap1pTktx8naf9vs9wMUCpFIgd6y4EfwDHlh3MkwvTZpKcP8-3EBZlVZfxESMshZVxlbT4zByYsHT1ubWirQFsyLATeRzr7kw5Dc-aQtJzyusya6HUwVy8I-RV4wuIyhvlt1OeS0RUBMf0TQS4XOiK8nlJqjj94oZKYODV-ei3JQCWLR5FGvjBkLKv-GITSKDuRFC7Bko9vCS3SWZqZ_9zP0Y6okoJEXpDQeQeYIHaF5R7Q8DykJ3r4xAA_aYgPn39Qvdm73VgwU9VWd5dRLw4jnBTr6jg',\n            'Accept': 'application/json'\n        }\n    \n        res = requests.post(url=\"https://appdev.keepz.me:8888/common-service/api/v1/auth/check\",\n                            data=data, headers=headers)\n    \n>       self.assertEquals(res.status_code, 200)\nE       AssertionError: 400 != 200\n\nTests\\auth_controller.py:24: AssertionError"}, "start": 1700047879691, "stop": 1700047880161, "uuid": "5780fce0-9818-477a-b49f-d41d7a5c61ec", "historyId": "42df1fd9a989db53c85ed9014bfc37fe", "testCaseId": "42df1fd9a989db53c85ed9014bfc37fe", "fullName": "Tests.auth_controller.AuthController#test_01_check", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "auth_controller"}, {"name": "subSuite", "value": "AuthController"}, {"name": "host", "value": "DESKTOP-MP62GBL"}, {"name": "thread", "value": "17464-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.auth_controller"}]}